//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	/// <summary>Konto</summary>
	[PublishedContentModel("account")]
	public partial class Account : PublishedContentModel, ISelectMenuOrFooter
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "account";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Account(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Account, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// GuestMenuText
		///</summary>
		[ImplementPropertyType("guestMenuText")]
		public string GuestMenuText
		{
			get { return this.GetPropertyValue<string>("guestMenuText"); }
		}

		///<summary>
		/// LoggedInMenuText
		///</summary>
		[ImplementPropertyType("loggedInMenuText")]
		public string LoggedInMenuText
		{
			get { return this.GetPropertyValue<string>("loggedInMenuText"); }
		}

		///<summary>
		/// Wybierz pozycję wyświetlenia sekcji
		///</summary>
		[ImplementPropertyType("choiceMenuOrFooter")]
		public nuPickers.Picker ChoiceMenuOrFooter
		{
			get { return SelectMenuOrFooter.GetChoiceMenuOrFooter(this); }
		}
	}
}
