//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	// Mixin content Type 1402 with alias "attachmentsControl"
	/// <summary>Załączniki</summary>
	public partial interface IAttachmentsControl : IPublishedContent
	{
		/// <summary>Lista załączników</summary>
		Archetype.Models.ArchetypeModel AttachmentsList { get; }
	}

	/// <summary>Załączniki</summary>
	[PublishedContentModel("attachmentsControl")]
	public partial class AttachmentsControl : PublishedContentModel, IAttachmentsControl
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "attachmentsControl";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public AttachmentsControl(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<AttachmentsControl, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Lista załączników
		///</summary>
		[ImplementPropertyType("attachmentsList")]
		public Archetype.Models.ArchetypeModel AttachmentsList
		{
			get { return GetAttachmentsList(this); }
		}

		/// <summary>Static getter for Lista załączników</summary>
		public static Archetype.Models.ArchetypeModel GetAttachmentsList(IAttachmentsControl that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("attachmentsList"); }
	}
}
