//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	// Mixin content Type 1297 with alias "cookies"
	/// <summary>Komunikat cookie</summary>
	public partial interface ICookies : IPublishedContent
	{
		/// <summary>Włączyć komunikat o cookies</summary>
		bool EnableCookies { get; }

		/// <summary>Treść</summary>
		IHtmlString Text { get; }
	}

	/// <summary>Komunikat cookie</summary>
	[PublishedContentModel("cookies")]
	public partial class Cookies : PublishedContentModel, ICookies
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "cookies";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Cookies(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Cookies, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Włączyć komunikat o cookies: Zaznacz aby włączyć komunikat o cookies
		///</summary>
		[ImplementPropertyType("enableCookies")]
		public bool EnableCookies
		{
			get { return GetEnableCookies(this); }
		}

		/// <summary>Static getter for Włączyć komunikat o cookies</summary>
		public static bool GetEnableCookies(ICookies that) { return that.GetPropertyValue<bool>("enableCookies"); }

		///<summary>
		/// Treść: Wprowadź tekst
		///</summary>
		[ImplementPropertyType("text")]
		public IHtmlString Text
		{
			get { return GetText(this); }
		}

		/// <summary>Static getter for Treść</summary>
		public static IHtmlString GetText(ICookies that) { return that.GetPropertyValue<IHtmlString>("text"); }
	}
}
