//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	// Mixin content Type 8417 with alias "hideableMenuItem"
	/// <summary>Ukrywalny Item Menu</summary>
	public partial interface IHideableMenuItem : IPublishedContent
	{
		/// <summary>IsHidden</summary>
		bool IsHidden { get; }
	}

	/// <summary>Ukrywalny Item Menu</summary>
	[PublishedContentModel("hideableMenuItem")]
	public partial class HideableMenuItem : PublishedContentModel, IHideableMenuItem
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "hideableMenuItem";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public HideableMenuItem(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<HideableMenuItem, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// IsHidden
		///</summary>
		[ImplementPropertyType("isHidden")]
		public bool IsHidden
		{
			get { return GetIsHidden(this); }
		}

		/// <summary>Static getter for IsHidden</summary>
		public static bool GetIsHidden(IHideableMenuItem that) { return that.GetPropertyValue<bool>("isHidden"); }
	}
}
