//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	/// <summary>Lokalizacja</summary>
	[PublishedContentModel("location")]
	public partial class Location : PublishedContentModel, ICookies, ISeo, ISiteUrl, ISocialMedia
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "location";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Location(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Location, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Link do strony BIP: Adres url do strony razem z http: np. http://www.bip.pl/example
		///</summary>
		[ImplementPropertyType("addBIPUrl")]
		public Newtonsoft.Json.Linq.JArray AddBipurl
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JArray>("addBIPUrl"); }
		}

		///<summary>
		/// Aktywny
		///</summary>
		[ImplementPropertyType("BannerActive")]
		public bool BannerActive
		{
			get { return this.GetPropertyValue<bool>("BannerActive"); }
		}

		///<summary>
		/// Otwórz w nowej karcie URL
		///</summary>
		[ImplementPropertyType("BannerButtonNewTab")]
		public bool BannerButtonNewTab
		{
			get { return this.GetPropertyValue<bool>("BannerButtonNewTab"); }
		}

		///<summary>
		/// Url przycisku
		///</summary>
		[ImplementPropertyType("BannerButtonUrl")]
		public string BannerButtonUrl
		{
			get { return this.GetPropertyValue<string>("BannerButtonUrl"); }
		}

		///<summary>
		/// Zdjęcie - tekst alternatywny
		///</summary>
		[ImplementPropertyType("BannerPictureAlt")]
		public string BannerPictureAlt
		{
			get { return this.GetPropertyValue<string>("BannerPictureAlt"); }
		}

		///<summary>
		/// Zdjęcie - Desktop: Zdjęcie które będzie wyświetlane w tle w przeglądarkach na komputerze
		///</summary>
		[ImplementPropertyType("BannerPictureDesktop")]
		public string BannerPictureDesktop
		{
			get { return this.GetPropertyValue<string>("BannerPictureDesktop"); }
		}

		///<summary>
		/// Zdjęcie - Mobile: Zdjęcie które będzie wyświetlane w tle w przeglądarkach na telefonie
		///</summary>
		[ImplementPropertyType("BannerPictureMobile")]
		public string BannerPictureMobile
		{
			get { return this.GetPropertyValue<string>("BannerPictureMobile"); }
		}

		///<summary>
		/// Dolnośląskie - aktualności
		///</summary>
		[ImplementPropertyType("dolnoslaskieAktualnosci")]
		public string DolnoslaskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("dolnoslaskieAktualnosci"); }
		}

		///<summary>
		/// Dolnośląskie - oferty
		///</summary>
		[ImplementPropertyType("dolnoslaskieOferty")]
		public string DolnoslaskieOferty
		{
			get { return this.GetPropertyValue<string>("dolnoslaskieOferty"); }
		}

		///<summary>
		/// Pierwsza linia tekstu na zdjęciu: Tutaj dodajemy pierwszą linię tekstu, znajdującą się na zdjęciu
		///</summary>
		[ImplementPropertyType("firstLineTextImage")]
		public string FirstLineTextImage
		{
			get { return this.GetPropertyValue<string>("firstLineTextImage"); }
		}

		///<summary>
		/// Tytuł sekcji pierwszej: Tutaj dodajemy tytuł sekcji pierwszej np. Oferty i promocje
		///</summary>
		[ImplementPropertyType("firstSectionName")]
		public string FirstSectionName
		{
			get { return this.GetPropertyValue<string>("firstSectionName"); }
		}

		///<summary>
		/// Numer telefonu infolinii: Podaj numer telefonu Infolinii
		///</summary>
		[ImplementPropertyType("helplineNumber")]
		public string HelplineNumber
		{
			get { return this.GetPropertyValue<string>("helplineNumber"); }
		}

		///<summary>
		/// Tooltip infolinii: Tekst wyświetlany na infolinii
		///</summary>
		[ImplementPropertyType("helplineTooltipText")]
		public IHtmlString HelplineTooltipText
		{
			get { return this.GetPropertyValue<IHtmlString>("helplineTooltipText"); }
		}

		///<summary>
		/// Zdjęcie główne: Tutaj dodajemy zdjęcie znajdujące się w górnej części na stronie głównej
		///</summary>
		[ImplementPropertyType("image")]
		public string Image
		{
			get { return this.GetPropertyValue<string>("image"); }
		}

		///<summary>
		/// Kujawsko-Pomorskie -aktualności: Aktualności w regionie Kujawsko - Pomorskim
		///</summary>
		[ImplementPropertyType("kujawskoPomorskieAktualnosci")]
		public string KujawskoPomorskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("kujawskoPomorskieAktualnosci"); }
		}

		///<summary>
		/// Kujawsko-Pomorskie -oferty: Oferty w regionie Kujawsko-Pomorskim
		///</summary>
		[ImplementPropertyType("kujawskoPomorskieOferty")]
		public string KujawskoPomorskieOferty
		{
			get { return this.GetPropertyValue<string>("kujawskoPomorskieOferty"); }
		}

		///<summary>
		/// Aktywny: Czy alert ma się wyświetlać na stronie
		///</summary>
		[ImplementPropertyType("LangAlertActive")]
		public bool LangAlertActive
		{
			get { return this.GetPropertyValue<bool>("LangAlertActive"); }
		}

		///<summary>
		/// Otwórz w nowej karcie URL
		///</summary>
		[ImplementPropertyType("LangAlertButtonNewTab")]
		public bool LangAlertButtonNewTab
		{
			get { return this.GetPropertyValue<bool>("LangAlertButtonNewTab"); }
		}

		///<summary>
		/// Tekst przycisku: Opcjonalny tekst na przycisku. Pozostaw puste aby nie wyświetlać przycisku.
		///</summary>
		[ImplementPropertyType("LangAlertButtonTitle")]
		public string LangAlertButtonTitle
		{
			get { return this.GetPropertyValue<string>("LangAlertButtonTitle"); }
		}

		///<summary>
		/// Url przycisku
		///</summary>
		[ImplementPropertyType("LangAlertButtonURL")]
		public string LangAlertButtonUrl
		{
			get { return this.GetPropertyValue<string>("LangAlertButtonURL"); }
		}

		///<summary>
		/// Treść alertu: Treść alertu która będzie się wyświetlać
		///</summary>
		[ImplementPropertyType("LangAlertTitle")]
		public string LangAlertTitle
		{
			get { return this.GetPropertyValue<string>("LangAlertTitle"); }
		}

		///<summary>
		/// Łódzkie - aktualności
		///</summary>
		[ImplementPropertyType("lodzkieAktualnosci")]
		public string LodzkieAktualnosci
		{
			get { return this.GetPropertyValue<string>("lodzkieAktualnosci"); }
		}

		///<summary>
		/// Łódzkie - oferty
		///</summary>
		[ImplementPropertyType("lodzkieOferty")]
		public string LodzkieOferty
		{
			get { return this.GetPropertyValue<string>("lodzkieOferty"); }
		}

		///<summary>
		/// Lubelskie - aktualności: Aktualności w regionie Lubelskim
		///</summary>
		[ImplementPropertyType("lubelskieAktualnosci")]
		public string LubelskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("lubelskieAktualnosci"); }
		}

		///<summary>
		/// Lubelskie - oferty: Oferty w regionie Lubelskim
		///</summary>
		[ImplementPropertyType("lubelskieOferty")]
		public string LubelskieOferty
		{
			get { return this.GetPropertyValue<string>("lubelskieOferty"); }
		}

		///<summary>
		/// Lubuskie - aktualności: Aktualności w regionie Lubuskim
		///</summary>
		[ImplementPropertyType("lubuskieAktualnosci")]
		public string LubuskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("lubuskieAktualnosci"); }
		}

		///<summary>
		/// Lubuskie - oferty: Oferty w regionie Lubuskim
		///</summary>
		[ImplementPropertyType("lubuskieOferty")]
		public string LubuskieOferty
		{
			get { return this.GetPropertyValue<string>("lubuskieOferty"); }
		}

		///<summary>
		/// Małopolskie - aktualności
		///</summary>
		[ImplementPropertyType("malopolskieAktualnosci")]
		public string MalopolskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("malopolskieAktualnosci"); }
		}

		///<summary>
		/// Małopolskie - oferty
		///</summary>
		[ImplementPropertyType("malopolskieOferty")]
		public string MalopolskieOferty
		{
			get { return this.GetPropertyValue<string>("malopolskieOferty"); }
		}

		///<summary>
		/// Mazowieckie - aktualności
		///</summary>
		[ImplementPropertyType("mazowieckieAktualnosci")]
		public string MazowieckieAktualnosci
		{
			get { return this.GetPropertyValue<string>("mazowieckieAktualnosci"); }
		}

		///<summary>
		/// Mazowieckie - oferty
		///</summary>
		[ImplementPropertyType("mazowieckieOferty")]
		public string MazowieckieOferty
		{
			get { return this.GetPropertyValue<string>("mazowieckieOferty"); }
		}

		///<summary>
		/// Aktualności: Wybierz artykuły które pokażą się na stronie głównej (od 0 do 4)
		///</summary>
		[ImplementPropertyType("news")]
		public string News
		{
			get { return this.GetPropertyValue<string>("news"); }
		}

		///<summary>
		/// Oferty: Wybierz oferty  które pokażą się na stronie głównej (od 0 do 4)
		///</summary>
		[ImplementPropertyType("offers")]
		public string Offers
		{
			get { return this.GetPropertyValue<string>("offers"); }
		}

		///<summary>
		/// Opolskie - aktualności
		///</summary>
		[ImplementPropertyType("opolskieAktualnosci")]
		public string OpolskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("opolskieAktualnosci"); }
		}

		///<summary>
		/// Opolskie - oferty
		///</summary>
		[ImplementPropertyType("opolskieOferty")]
		public string OpolskieOferty
		{
			get { return this.GetPropertyValue<string>("opolskieOferty"); }
		}

		///<summary>
		/// Otwórz w nowej karcie URL
		///</summary>
		[ImplementPropertyType("OverlayButtonNewTab")]
		public bool OverlayButtonNewTab
		{
			get { return this.GetPropertyValue<bool>("OverlayButtonNewTab"); }
		}

		///<summary>
		/// Url przycisku
		///</summary>
		[ImplementPropertyType("OverlayButtonUrl")]
		public string OverlayButtonUrl
		{
			get { return this.GetPropertyValue<string>("OverlayButtonUrl"); }
		}

		///<summary>
		/// Capping: Określa ile razy danemu użytkownikowi ma się wyświetlić overlay
		///</summary>
		[ImplementPropertyType("OverlayCapping")]
		public string OverlayCapping
		{
			get { return this.GetPropertyValue<string>("OverlayCapping"); }
		}

		///<summary>
		/// Zdjęcie - tekst alternatywny: Tekst alternatywny dla zdjęcia, wykorzystywany w przypadku kiedy zdjęcie się nie załaduje lub dla osób niewidomych
		///</summary>
		[ImplementPropertyType("OverlayPictureAlt")]
		public string OverlayPictureAlt
		{
			get { return this.GetPropertyValue<string>("OverlayPictureAlt"); }
		}

		///<summary>
		/// Zdjęcie - Desktop: Zdjęcie które będzie wyświetlane w tle w przeglądarkach na komputerze
		///</summary>
		[ImplementPropertyType("OverlayPictureDesktop")]
		public string OverlayPictureDesktop
		{
			get { return this.GetPropertyValue<string>("OverlayPictureDesktop"); }
		}

		///<summary>
		/// Zdjęcie - Mobile: Zdjęcie które będzie wyświetlane w tle w przeglądarkach na telefonie
		///</summary>
		[ImplementPropertyType("OverlayPictureMobile")]
		public string OverlayPictureMobile
		{
			get { return this.GetPropertyValue<string>("OverlayPictureMobile"); }
		}

		///<summary>
		/// Wyświetlanie overlay'a
		///</summary>
		[ImplementPropertyType("OverlayShowOn")]
		public object OverlayShowOn
		{
			get { return this.GetPropertyValue("OverlayShowOn"); }
		}

		///<summary>
		/// Kategorie wyświetlania overlaya
		///</summary>
		[ImplementPropertyType("OverlayShowOnNodes")]
		public string OverlayShowOnNodes
		{
			get { return this.GetPropertyValue<string>("OverlayShowOnNodes"); }
		}

		///<summary>
		/// Podkarpackie -aktualności
		///</summary>
		[ImplementPropertyType("podkarpackieAktualnosci")]
		public string PodkarpackieAktualnosci
		{
			get { return this.GetPropertyValue<string>("podkarpackieAktualnosci"); }
		}

		///<summary>
		/// Podkarpackie - oferty
		///</summary>
		[ImplementPropertyType("podkarpackieOferty")]
		public string PodkarpackieOferty
		{
			get { return this.GetPropertyValue<string>("podkarpackieOferty"); }
		}

		///<summary>
		/// Podlaskie - aktualności
		///</summary>
		[ImplementPropertyType("podlaskieAktualnosci")]
		public string PodlaskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("podlaskieAktualnosci"); }
		}

		///<summary>
		/// Podlaskie - oferty
		///</summary>
		[ImplementPropertyType("podlaskieOferty")]
		public string PodlaskieOferty
		{
			get { return this.GetPropertyValue<string>("podlaskieOferty"); }
		}

		///<summary>
		/// Pomorskie - aktualności
		///</summary>
		[ImplementPropertyType("pomorskieAktualnosci")]
		public string PomorskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("pomorskieAktualnosci"); }
		}

		///<summary>
		/// Pomorskie - oferty
		///</summary>
		[ImplementPropertyType("pomorskieOferty")]
		public string PomorskieOferty
		{
			get { return this.GetPropertyValue<string>("pomorskieOferty"); }
		}

		///<summary>
		/// Druga linia tekstu na zdjęciu: Tutaj dodajemy drugą linię tekst znajdującą się na zdjęciu
		///</summary>
		[ImplementPropertyType("secondLineTextImage")]
		public string SecondLineTextImage
		{
			get { return this.GetPropertyValue<string>("secondLineTextImage"); }
		}

		///<summary>
		/// Tytuł sekcji drugiej: Tutaj dodajemy tytuł sekcji drugiej np. Aktualności
		///</summary>
		[ImplementPropertyType("secondSectionName")]
		public string SecondSectionName
		{
			get { return this.GetPropertyValue<string>("secondSectionName"); }
		}

		///<summary>
		/// Śląskie - aktualności
		///</summary>
		[ImplementPropertyType("slaskieAktualnosci")]
		public string SlaskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("slaskieAktualnosci"); }
		}

		///<summary>
		/// Śląskie - oferty
		///</summary>
		[ImplementPropertyType("slaskieOferty")]
		public string SlaskieOferty
		{
			get { return this.GetPropertyValue<string>("slaskieOferty"); }
		}

		///<summary>
		/// Świętokrzystkie - aktualności
		///</summary>
		[ImplementPropertyType("swietokrzystkieAktualnosci")]
		public string SwietokrzystkieAktualnosci
		{
			get { return this.GetPropertyValue<string>("swietokrzystkieAktualnosci"); }
		}

		///<summary>
		/// Świętokrzystkie - oferty
		///</summary>
		[ImplementPropertyType("swietokrzystkieOferty")]
		public string SwietokrzystkieOferty
		{
			get { return this.GetPropertyValue<string>("swietokrzystkieOferty"); }
		}

		///<summary>
		/// Warmińsko-Mazurskie - aktualności
		///</summary>
		[ImplementPropertyType("warminskoMazurskieAktualnosci")]
		public string WarminskoMazurskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("warminskoMazurskieAktualnosci"); }
		}

		///<summary>
		/// Warmińsko-Mazurskie - oferty
		///</summary>
		[ImplementPropertyType("warminskoMazurskieOferty")]
		public string WarminskoMazurskieOferty
		{
			get { return this.GetPropertyValue<string>("warminskoMazurskieOferty"); }
		}

		///<summary>
		/// Wielkopolskie - aktualności
		///</summary>
		[ImplementPropertyType("wielkopolskieAktualnosci")]
		public string WielkopolskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("wielkopolskieAktualnosci"); }
		}

		///<summary>
		/// Wielkopolskie - oferty
		///</summary>
		[ImplementPropertyType("wielkopolskieOferty")]
		public string WielkopolskieOferty
		{
			get { return this.GetPropertyValue<string>("wielkopolskieOferty"); }
		}

		///<summary>
		/// Zachodniopomorskie - aktualności
		///</summary>
		[ImplementPropertyType("zachodniopomorskieAktualnosci")]
		public string ZachodniopomorskieAktualnosci
		{
			get { return this.GetPropertyValue<string>("zachodniopomorskieAktualnosci"); }
		}

		///<summary>
		/// Zachodniopomorskie - oferty
		///</summary>
		[ImplementPropertyType("zachodniopomorskieOferty")]
		public string ZachodniopomorskieOferty
		{
			get { return this.GetPropertyValue<string>("zachodniopomorskieOferty"); }
		}

		///<summary>
		/// Włączyć komunikat o cookies: Zaznacz aby włączyć komunikat o cookies
		///</summary>
		[ImplementPropertyType("enableCookies")]
		public bool EnableCookies
		{
			get { return Cookies.GetEnableCookies(this); }
		}

		///<summary>
		/// Treść: Wprowadź tekst
		///</summary>
		[ImplementPropertyType("text")]
		public IHtmlString Text
		{
			get { return Cookies.GetText(this); }
		}

		///<summary>
		/// Meta description: Tekst zostanie dodany do meta description
		///</summary>
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription
		{
			get { return Seo.GetMetaDescription(this); }
		}

		///<summary>
		/// Open Graph description: Tekst zostanie dodany do og:Description
		///</summary>
		[ImplementPropertyType("ogDescription")]
		public string OgDescription
		{
			get { return Seo.GetOgDescription(this); }
		}

		///<summary>
		/// Open Graph image: Ulr zostanie dodany do og:Image
		///</summary>
		[ImplementPropertyType("ogImage")]
		public string OgImage
		{
			get { return Seo.GetOgImage(this); }
		}

		///<summary>
		/// Open Graph title: Tekst zostanie dodany do og:Title
		///</summary>
		[ImplementPropertyType("ogTitle")]
		public string OgTitle
		{
			get { return Seo.GetOgTitle(this); }
		}

		///<summary>
		/// Page Title: Tytuł strony wyświetlany an pasku w przeglądarce
		///</summary>
		[ImplementPropertyType("pageTitle")]
		public string PageTitle
		{
			get { return Seo.GetPageTitle(this); }
		}

		///<summary>
		/// Alias strony
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return SiteUrl.GetUmbracoUrlAlias(this); }
		}

		///<summary>
		/// Url do strony: Adres url pod jakim będzie wyświetlana ta strona
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return SiteUrl.GetUmbracoUrlName(this); }
		}

		///<summary>
		/// Lista elementów do social media
		///</summary>
		[ImplementPropertyType("socialMediaElementList")]
		public Archetype.Models.ArchetypeModel SocialMediaElementList
		{
			get { return SocialMedia.GetSocialMediaElementList(this); }
		}
	}
}
