//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	// Mixin content Type 1375 with alias "mainPageDataWithList"
	/// <summary>Dane podstawowe strony</summary>
	public partial interface IMainPageDataWithList : IPublishedContent
	{
		/// <summary>Lista wyświetlanych elementów</summary>
		int DisplayItemCount { get; }

		/// <summary>Tytuł na stronie</summary>
		string PageMainTitle { get; }
	}

	/// <summary>Dane podstawowe strony</summary>
	[PublishedContentModel("mainPageDataWithList")]
	public partial class MainPageDataWithList : PublishedContentModel, IMainPageDataWithList
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "mainPageDataWithList";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public MainPageDataWithList(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<MainPageDataWithList, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Lista wyświetlanych elementów
		///</summary>
		[ImplementPropertyType("displayItemCount")]
		public int DisplayItemCount
		{
			get { return GetDisplayItemCount(this); }
		}

		/// <summary>Static getter for Lista wyświetlanych elementów</summary>
		public static int GetDisplayItemCount(IMainPageDataWithList that) { return that.GetPropertyValue<int>("displayItemCount"); }

		///<summary>
		/// Tytuł na stronie
		///</summary>
		[ImplementPropertyType("pageMainTitle")]
		public string PageMainTitle
		{
			get { return GetPageMainTitle(this); }
		}

		/// <summary>Static getter for Tytuł na stronie</summary>
		public static string GetPageMainTitle(IMainPageDataWithList that) { return that.GetPropertyValue<string>("pageMainTitle"); }
	}
}
