//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	// Mixin content Type 1394 with alias "noticesFiltr"
	/// <summary>Filtr zamówień</summary>
	public partial interface INoticesFiltr : IPublishedContent
	{
		/// <summary>Jednostka administracyjna</summary>
		nuPickers.Picker Administrative { get; }

		/// <summary>Termin składania ofert/wniosków</summary>
		DateTime DateLimitForReceipt { get; }

		/// <summary>Data wszczęcia</summary>
		DateTime InitiationOfProceedingsDate { get; }

		/// <summary>Akt prawny</summary>
		nuPickers.Picker LawAct { get; }

		/// <summary>Nazwa postępowania</summary>
		string NameOfProceedings { get; }

		/// <summary>Numer postępowania</summary>
		string NumberOfProceedings { get; }

		/// <summary>Rodzaj zamówienia</summary>
		nuPickers.Picker TypeOfContract { get; }
	}

	/// <summary>Filtr zamówień</summary>
	[PublishedContentModel("noticesFiltr")]
	public partial class NoticesFiltr : PublishedContentModel, INoticesFiltr
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "noticesFiltr";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public NoticesFiltr(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<NoticesFiltr, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Jednostka administracyjna
		///</summary>
		[ImplementPropertyType("administrative")]
		public nuPickers.Picker Administrative
		{
			get { return GetAdministrative(this); }
		}

		/// <summary>Static getter for Jednostka administracyjna</summary>
		public static nuPickers.Picker GetAdministrative(INoticesFiltr that) { return that.GetPropertyValue<nuPickers.Picker>("administrative"); }

		///<summary>
		/// Termin składania ofert/wniosków
		///</summary>
		[ImplementPropertyType("dateLimitForReceipt")]
		public DateTime DateLimitForReceipt
		{
			get { return GetDateLimitForReceipt(this); }
		}

		/// <summary>Static getter for Termin składania ofert/wniosków</summary>
		public static DateTime GetDateLimitForReceipt(INoticesFiltr that) { return that.GetPropertyValue<DateTime>("dateLimitForReceipt"); }

		///<summary>
		/// Data wszczęcia
		///</summary>
		[ImplementPropertyType("initiationOfProceedingsDate")]
		public DateTime InitiationOfProceedingsDate
		{
			get { return GetInitiationOfProceedingsDate(this); }
		}

		/// <summary>Static getter for Data wszczęcia</summary>
		public static DateTime GetInitiationOfProceedingsDate(INoticesFiltr that) { return that.GetPropertyValue<DateTime>("initiationOfProceedingsDate"); }

		///<summary>
		/// Akt prawny
		///</summary>
		[ImplementPropertyType("lawAct")]
		public nuPickers.Picker LawAct
		{
			get { return GetLawAct(this); }
		}

		/// <summary>Static getter for Akt prawny</summary>
		public static nuPickers.Picker GetLawAct(INoticesFiltr that) { return that.GetPropertyValue<nuPickers.Picker>("lawAct"); }

		///<summary>
		/// Nazwa postępowania
		///</summary>
		[ImplementPropertyType("nameOfProceedings")]
		public string NameOfProceedings
		{
			get { return GetNameOfProceedings(this); }
		}

		/// <summary>Static getter for Nazwa postępowania</summary>
		public static string GetNameOfProceedings(INoticesFiltr that) { return that.GetPropertyValue<string>("nameOfProceedings"); }

		///<summary>
		/// Numer postępowania
		///</summary>
		[ImplementPropertyType("numberOfProceedings")]
		public string NumberOfProceedings
		{
			get { return GetNumberOfProceedings(this); }
		}

		/// <summary>Static getter for Numer postępowania</summary>
		public static string GetNumberOfProceedings(INoticesFiltr that) { return that.GetPropertyValue<string>("numberOfProceedings"); }

		///<summary>
		/// Rodzaj zamówienia
		///</summary>
		[ImplementPropertyType("typeOfContract")]
		public nuPickers.Picker TypeOfContract
		{
			get { return GetTypeOfContract(this); }
		}

		/// <summary>Static getter for Rodzaj zamówienia</summary>
		public static nuPickers.Picker GetTypeOfContract(INoticesFiltr that) { return that.GetPropertyValue<nuPickers.Picker>("typeOfContract"); }
	}
}
