//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	/// <summary>Odbiory maila z powiadomieniami o artykule</summary>
	[PublishedContentModel("odbioryMailaZPowiadomieniamiOArtykule")]
	public partial class OdbioryMailaZpowiadomieniamiOartykule : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "odbioryMailaZPowiadomieniamiOArtykule";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public OdbioryMailaZpowiadomieniamiOartykule(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<OdbioryMailaZpowiadomieniamiOartykule, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Artykuły: Wybierz artykuły dla których zostaną wysłane powiadomienia
		///</summary>
		[ImplementPropertyType("artykuly")]
		public string Artykuly
		{
			get { return this.GetPropertyValue<string>("artykuly"); }
		}
	}
}
