//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.4.0
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace PolRegio.Domain.Models.UmbracoCreate
{
	// Mixin content Type 1215 with alias "socialMedia"
	/// <summary>Media społecznościowe</summary>
	public partial interface ISocialMedia : IPublishedContent
	{
		/// <summary>Lista elementów do social media</summary>
		Archetype.Models.ArchetypeModel SocialMediaElementList { get; }
	}

	/// <summary>Media społecznościowe</summary>
	[PublishedContentModel("socialMedia")]
	public partial class SocialMedia : PublishedContentModel, ISocialMedia
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "socialMedia";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SocialMedia(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SocialMedia, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Lista elementów do social media
		///</summary>
		[ImplementPropertyType("socialMediaElementList")]
		public Archetype.Models.ArchetypeModel SocialMediaElementList
		{
			get { return GetSocialMediaElementList(this); }
		}

		/// <summary>Static getter for Lista elementów do social media</summary>
		public static Archetype.Models.ArchetypeModel GetSocialMediaElementList(ISocialMedia that) { return that.GetPropertyValue<Archetype.Models.ArchetypeModel>("socialMediaElementList"); }
	}
}
